//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.18 at 07:50:28 PM EDT 
//


package com.alagad.ColdBooks.US.v110;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ListEventType"/>
 *         &lt;element ref="{}ListEventOperation"/>
 *         &lt;element ref="{}ListID"/>
 *         &lt;element ref="{}AfterMergeListID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listEventType",
    "listEventOperation",
    "listID",
    "afterMergeListID"
})
@XmlRootElement(name = "ListEvent")
public class ListEvent {

    @XmlElement(name = "ListEventType", required = true)
    protected String listEventType;
    @XmlElement(name = "ListEventOperation", required = true)
    protected String listEventOperation;
    @XmlElement(name = "ListID", required = true)
    protected String listID;
    @XmlElement(name = "AfterMergeListID")
    protected String afterMergeListID;

    /**
     * Gets the value of the listEventType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListEventType() {
        return listEventType;
    }

    /**
     * Sets the value of the listEventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListEventType(String value) {
        this.listEventType = value;
    }

    /**
     * Gets the value of the listEventOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListEventOperation() {
        return listEventOperation;
    }

    /**
     * Sets the value of the listEventOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListEventOperation(String value) {
        this.listEventOperation = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListID(String value) {
        this.listID = value;
    }

    /**
     * Gets the value of the afterMergeListID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfterMergeListID() {
        return afterMergeListID;
    }

    /**
     * Sets the value of the afterMergeListID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfterMergeListID(String value) {
        this.afterMergeListID = value;
    }

}
