//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.06 at 08:58:36 PM EST 
//


package com.alagad.ColdBooks.CA.v20;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ChargeTax1"/>
 *         &lt;element ref="{}TrackTax1Expenses"/>
 *         &lt;element ref="{}Tax1Number"/>
 *         &lt;element ref="{}Tax1AgencyRef"/>
 *         &lt;element ref="{}Tax1ReportingPeriod"/>
 *         &lt;element ref="{}ChargeTax2"/>
 *         &lt;element ref="{}TrackTax2Expenses"/>
 *         &lt;element ref="{}Tax2Number"/>
 *         &lt;element ref="{}Tax2AgencyRef"/>
 *         &lt;element ref="{}Tax2ReportingPeriod"/>
 *         &lt;element ref="{}AllowCustomerTaxCodes"/>
 *         &lt;element ref="{}DefaultCustomerTaxCodeRef"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chargeTax1",
    "trackTax1Expenses",
    "tax1Number",
    "tax1AgencyRef",
    "tax1ReportingPeriod",
    "chargeTax2",
    "trackTax2Expenses",
    "tax2Number",
    "tax2AgencyRef",
    "tax2ReportingPeriod",
    "allowCustomerTaxCodes",
    "defaultCustomerTaxCodeRef"
})
@XmlRootElement(name = "TaxPreferences")
public class TaxPreferences {

    @XmlElement(name = "ChargeTax1", required = true)
    protected String chargeTax1;
    @XmlElement(name = "TrackTax1Expenses", required = true)
    protected String trackTax1Expenses;
    @XmlElement(name = "Tax1Number", required = true)
    protected String tax1Number;
    @XmlElement(name = "Tax1AgencyRef", required = true)
    protected Tax1AgencyRef tax1AgencyRef;
    @XmlElement(name = "Tax1ReportingPeriod", required = true)
    protected String tax1ReportingPeriod;
    @XmlElement(name = "ChargeTax2", required = true)
    protected String chargeTax2;
    @XmlElement(name = "TrackTax2Expenses", required = true)
    protected String trackTax2Expenses;
    @XmlElement(name = "Tax2Number", required = true)
    protected String tax2Number;
    @XmlElement(name = "Tax2AgencyRef", required = true)
    protected Tax2AgencyRef tax2AgencyRef;
    @XmlElement(name = "Tax2ReportingPeriod", required = true)
    protected String tax2ReportingPeriod;
    @XmlElement(name = "AllowCustomerTaxCodes", required = true)
    protected String allowCustomerTaxCodes;
    @XmlElement(name = "DefaultCustomerTaxCodeRef", required = true)
    protected DefaultCustomerTaxCodeRef defaultCustomerTaxCodeRef;

    /**
     * Gets the value of the chargeTax1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeTax1() {
        return chargeTax1;
    }

    /**
     * Sets the value of the chargeTax1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeTax1(String value) {
        this.chargeTax1 = value;
    }

    /**
     * Gets the value of the trackTax1Expenses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackTax1Expenses() {
        return trackTax1Expenses;
    }

    /**
     * Sets the value of the trackTax1Expenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackTax1Expenses(String value) {
        this.trackTax1Expenses = value;
    }

    /**
     * Gets the value of the tax1Number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTax1Number() {
        return tax1Number;
    }

    /**
     * Sets the value of the tax1Number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTax1Number(String value) {
        this.tax1Number = value;
    }

    /**
     * Gets the value of the tax1AgencyRef property.
     * 
     * @return
     *     possible object is
     *     {@link Tax1AgencyRef }
     *     
     */
    public Tax1AgencyRef getTax1AgencyRef() {
        return tax1AgencyRef;
    }

    /**
     * Sets the value of the tax1AgencyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tax1AgencyRef }
     *     
     */
    public void setTax1AgencyRef(Tax1AgencyRef value) {
        this.tax1AgencyRef = value;
    }

    /**
     * Gets the value of the tax1ReportingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTax1ReportingPeriod() {
        return tax1ReportingPeriod;
    }

    /**
     * Sets the value of the tax1ReportingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTax1ReportingPeriod(String value) {
        this.tax1ReportingPeriod = value;
    }

    /**
     * Gets the value of the chargeTax2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeTax2() {
        return chargeTax2;
    }

    /**
     * Sets the value of the chargeTax2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeTax2(String value) {
        this.chargeTax2 = value;
    }

    /**
     * Gets the value of the trackTax2Expenses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackTax2Expenses() {
        return trackTax2Expenses;
    }

    /**
     * Sets the value of the trackTax2Expenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackTax2Expenses(String value) {
        this.trackTax2Expenses = value;
    }

    /**
     * Gets the value of the tax2Number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTax2Number() {
        return tax2Number;
    }

    /**
     * Sets the value of the tax2Number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTax2Number(String value) {
        this.tax2Number = value;
    }

    /**
     * Gets the value of the tax2AgencyRef property.
     * 
     * @return
     *     possible object is
     *     {@link Tax2AgencyRef }
     *     
     */
    public Tax2AgencyRef getTax2AgencyRef() {
        return tax2AgencyRef;
    }

    /**
     * Sets the value of the tax2AgencyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tax2AgencyRef }
     *     
     */
    public void setTax2AgencyRef(Tax2AgencyRef value) {
        this.tax2AgencyRef = value;
    }

    /**
     * Gets the value of the tax2ReportingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTax2ReportingPeriod() {
        return tax2ReportingPeriod;
    }

    /**
     * Sets the value of the tax2ReportingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTax2ReportingPeriod(String value) {
        this.tax2ReportingPeriod = value;
    }

    /**
     * Gets the value of the allowCustomerTaxCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowCustomerTaxCodes() {
        return allowCustomerTaxCodes;
    }

    /**
     * Sets the value of the allowCustomerTaxCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowCustomerTaxCodes(String value) {
        this.allowCustomerTaxCodes = value;
    }

    /**
     * Gets the value of the defaultCustomerTaxCodeRef property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultCustomerTaxCodeRef }
     *     
     */
    public DefaultCustomerTaxCodeRef getDefaultCustomerTaxCodeRef() {
        return defaultCustomerTaxCodeRef;
    }

    /**
     * Sets the value of the defaultCustomerTaxCodeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultCustomerTaxCodeRef }
     *     
     */
    public void setDefaultCustomerTaxCodeRef(DefaultCustomerTaxCodeRef value) {
        this.defaultCustomerTaxCodeRef = value;
    }

}
