//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.06 at 09:02:45 PM EST 
//


package com.alagad.ColdBooks.US.v40;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DefaultItemSalesTaxRef"/>
 *         &lt;element ref="{}PaySalesTax"/>
 *         &lt;element ref="{}DefaultTaxableSalesTaxCodeRef"/>
 *         &lt;element ref="{}DefaultNonTaxableSalesTaxCodeRef"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "defaultItemSalesTaxRef",
    "paySalesTax",
    "defaultTaxableSalesTaxCodeRef",
    "defaultNonTaxableSalesTaxCodeRef"
})
@XmlRootElement(name = "SalesTaxPreferences")
public class SalesTaxPreferences {

    @XmlElement(name = "DefaultItemSalesTaxRef", required = true)
    protected DefaultItemSalesTaxRef defaultItemSalesTaxRef;
    @XmlElement(name = "PaySalesTax", required = true)
    protected String paySalesTax;
    @XmlElement(name = "DefaultTaxableSalesTaxCodeRef", required = true)
    protected DefaultTaxableSalesTaxCodeRef defaultTaxableSalesTaxCodeRef;
    @XmlElement(name = "DefaultNonTaxableSalesTaxCodeRef", required = true)
    protected DefaultNonTaxableSalesTaxCodeRef defaultNonTaxableSalesTaxCodeRef;

    /**
     * Gets the value of the defaultItemSalesTaxRef property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultItemSalesTaxRef }
     *     
     */
    public DefaultItemSalesTaxRef getDefaultItemSalesTaxRef() {
        return defaultItemSalesTaxRef;
    }

    /**
     * Sets the value of the defaultItemSalesTaxRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultItemSalesTaxRef }
     *     
     */
    public void setDefaultItemSalesTaxRef(DefaultItemSalesTaxRef value) {
        this.defaultItemSalesTaxRef = value;
    }

    /**
     * Gets the value of the paySalesTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaySalesTax() {
        return paySalesTax;
    }

    /**
     * Sets the value of the paySalesTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaySalesTax(String value) {
        this.paySalesTax = value;
    }

    /**
     * Gets the value of the defaultTaxableSalesTaxCodeRef property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultTaxableSalesTaxCodeRef }
     *     
     */
    public DefaultTaxableSalesTaxCodeRef getDefaultTaxableSalesTaxCodeRef() {
        return defaultTaxableSalesTaxCodeRef;
    }

    /**
     * Sets the value of the defaultTaxableSalesTaxCodeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultTaxableSalesTaxCodeRef }
     *     
     */
    public void setDefaultTaxableSalesTaxCodeRef(DefaultTaxableSalesTaxCodeRef value) {
        this.defaultTaxableSalesTaxCodeRef = value;
    }

    /**
     * Gets the value of the defaultNonTaxableSalesTaxCodeRef property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultNonTaxableSalesTaxCodeRef }
     *     
     */
    public DefaultNonTaxableSalesTaxCodeRef getDefaultNonTaxableSalesTaxCodeRef() {
        return defaultNonTaxableSalesTaxCodeRef;
    }

    /**
     * Sets the value of the defaultNonTaxableSalesTaxCodeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultNonTaxableSalesTaxCodeRef }
     *     
     */
    public void setDefaultNonTaxableSalesTaxCodeRef(DefaultNonTaxableSalesTaxCodeRef value) {
        this.defaultNonTaxableSalesTaxCodeRef = value;
    }

}
