//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.06 at 08:59:32 PM EST 
//


package com.alagad.ColdBooks.UK.v20;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmployeeAddRqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmployeeAddRqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EmployeeAdd"/>
 *       &lt;/sequence>
 *       &lt;attribute name="requestID" type="{}STRTYPE" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmployeeAddRqType", propOrder = {
    "employeeAdd"
})
public class EmployeeAddRqType {

    @XmlElement(name = "EmployeeAdd", required = true)
    protected EmployeeAdd employeeAdd;
    @XmlAttribute
    protected String requestID;

    /**
     * Gets the value of the employeeAdd property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeAdd }
     *     
     */
    public EmployeeAdd getEmployeeAdd() {
        return employeeAdd;
    }

    /**
     * Sets the value of the employeeAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeAdd }
     *     
     */
    public void setEmployeeAdd(EmployeeAdd value) {
        this.employeeAdd = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }

}
