//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.18 at 07:52:02 PM EDT 
//


package com.alagad.ColdBooks.UK.v110;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemQueryRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemQueryRsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}ItemServiceRet"/>
 *           &lt;element ref="{}ItemNonInventoryRet"/>
 *           &lt;element ref="{}ItemOtherChargeRet"/>
 *           &lt;element ref="{}ItemInventoryRet"/>
 *           &lt;element ref="{}ItemInventoryAssemblyRet"/>
 *           &lt;element ref="{}ItemFixedAssetRet"/>
 *           &lt;element ref="{}ItemSubtotalRet"/>
 *           &lt;element ref="{}ItemDiscountRet"/>
 *           &lt;element ref="{}ItemPaymentRet"/>
 *           &lt;element ref="{}ItemSalesTaxRet"/>
 *           &lt;element ref="{}ItemSalesTaxGroupRet"/>
 *           &lt;element ref="{}ItemGroupRet"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="requestID" type="{}STRTYPE" />
 *       &lt;attribute name="statusCode" use="required" type="{}INTTYPE" />
 *       &lt;attribute name="statusSeverity" use="required" type="{}STRTYPE" />
 *       &lt;attribute name="statusMessage" type="{}STRTYPE" />
 *       &lt;attribute name="retCount" type="{}INTTYPE" />
 *       &lt;attribute name="iteratorRemainingCount" type="{}INTTYPE" />
 *       &lt;attribute name="iteratorID" type="{}STRTYPE" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemQueryRsType", propOrder = {
    "itemServiceRetOrItemNonInventoryRetOrItemOtherChargeRet"
})
public class ItemQueryRsType {

    @XmlElements({
        @XmlElement(name = "ItemSubtotalRet", type = ItemSubtotalRet.class),
        @XmlElement(name = "ItemPaymentRet", type = ItemPaymentRet.class),
        @XmlElement(name = "ItemDiscountRet", type = ItemDiscountRet.class),
        @XmlElement(name = "ItemInventoryAssemblyRet", type = ItemInventoryAssemblyRet.class),
        @XmlElement(name = "ItemGroupRet", type = ItemGroupRet.class),
        @XmlElement(name = "ItemFixedAssetRet", type = ItemFixedAssetRet.class),
        @XmlElement(name = "ItemSalesTaxGroupRet", type = ItemSalesTaxGroupRet.class),
        @XmlElement(name = "ItemNonInventoryRet", type = ItemNonInventoryRet.class),
        @XmlElement(name = "ItemInventoryRet", type = ItemInventoryRet.class),
        @XmlElement(name = "ItemServiceRet", type = ItemServiceRet.class),
        @XmlElement(name = "ItemSalesTaxRet", type = ItemSalesTaxRet.class),
        @XmlElement(name = "ItemOtherChargeRet", type = ItemOtherChargeRet.class)
    })
    protected List<Object> itemServiceRetOrItemNonInventoryRetOrItemOtherChargeRet;
    @XmlAttribute
    protected String requestID;
    @XmlAttribute(required = true)
    protected BigInteger statusCode;
    @XmlAttribute(required = true)
    protected String statusSeverity;
    @XmlAttribute
    protected String statusMessage;
    @XmlAttribute
    protected BigInteger retCount;
    @XmlAttribute
    protected BigInteger iteratorRemainingCount;
    @XmlAttribute
    protected String iteratorID;

    /**
     * Gets the value of the itemServiceRetOrItemNonInventoryRetOrItemOtherChargeRet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemServiceRetOrItemNonInventoryRetOrItemOtherChargeRet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemServiceRetOrItemNonInventoryRetOrItemOtherChargeRet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemSubtotalRet }
     * {@link ItemPaymentRet }
     * {@link ItemDiscountRet }
     * {@link ItemInventoryAssemblyRet }
     * {@link ItemGroupRet }
     * {@link ItemFixedAssetRet }
     * {@link ItemSalesTaxGroupRet }
     * {@link ItemNonInventoryRet }
     * {@link ItemInventoryRet }
     * {@link ItemServiceRet }
     * {@link ItemSalesTaxRet }
     * {@link ItemOtherChargeRet }
     * 
     * 
     */
    public List<Object> getItemServiceRetOrItemNonInventoryRetOrItemOtherChargeRet() {
        if (itemServiceRetOrItemNonInventoryRetOrItemOtherChargeRet == null) {
            itemServiceRetOrItemNonInventoryRetOrItemOtherChargeRet = new ArrayList<Object>();
        }
        return this.itemServiceRetOrItemNonInventoryRetOrItemOtherChargeRet;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatusCode(BigInteger value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusSeverity() {
        return statusSeverity;
    }

    /**
     * Sets the value of the statusSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusSeverity(String value) {
        this.statusSeverity = value;
    }

    /**
     * Gets the value of the statusMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMessage(String value) {
        this.statusMessage = value;
    }

    /**
     * Gets the value of the retCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRetCount() {
        return retCount;
    }

    /**
     * Sets the value of the retCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRetCount(BigInteger value) {
        this.retCount = value;
    }

    /**
     * Gets the value of the iteratorRemainingCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIteratorRemainingCount() {
        return iteratorRemainingCount;
    }

    /**
     * Sets the value of the iteratorRemainingCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIteratorRemainingCount(BigInteger value) {
        this.iteratorRemainingCount = value;
    }

    /**
     * Gets the value of the iteratorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIteratorID() {
        return iteratorID;
    }

    /**
     * Sets the value of the iteratorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIteratorID(String value) {
        this.iteratorID = value;
    }

}
