//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.18 at 07:52:02 PM EDT 
//


package com.alagad.ColdBooks.UK.v110;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PaymentScheduleType"/>
 *         &lt;element ref="{}PaymentDueNumDaysAfter" minOccurs="0"/>
 *         &lt;element ref="{}PaymentDueDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymentScheduleType",
    "paymentDueNumDaysAfter",
    "paymentDueDate"
})
@XmlRootElement(name = "LiabilityPaymentSchedule")
public class LiabilityPaymentSchedule {

    @XmlElement(name = "PaymentScheduleType", required = true)
    protected String paymentScheduleType;
    @XmlElement(name = "PaymentDueNumDaysAfter")
    protected BigInteger paymentDueNumDaysAfter;
    @XmlElement(name = "PaymentDueDate")
    protected String paymentDueDate;

    /**
     * Gets the value of the paymentScheduleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentScheduleType() {
        return paymentScheduleType;
    }

    /**
     * Sets the value of the paymentScheduleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentScheduleType(String value) {
        this.paymentScheduleType = value;
    }

    /**
     * Gets the value of the paymentDueNumDaysAfter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaymentDueNumDaysAfter() {
        return paymentDueNumDaysAfter;
    }

    /**
     * Sets the value of the paymentDueNumDaysAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaymentDueNumDaysAfter(BigInteger value) {
        this.paymentDueNumDaysAfter = value;
    }

    /**
     * Gets the value of the paymentDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentDueDate() {
        return paymentDueDate;
    }

    /**
     * Sets the value of the paymentDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDueDate(String value) {
        this.paymentDueDate = value;
    }

}
