//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.18 at 07:52:02 PM EDT 
//


package com.alagad.ColdBooks.UK.v110;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DefaultShipMethodRef" minOccurs="0"/>
 *         &lt;element name="DefaultFOB" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{}STRTYPE">
 *               &lt;maxLength value="13"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{}DefaultMarkup" minOccurs="0"/>
 *         &lt;element ref="{}IsTrackingReimbursedExpensesAsIncome"/>
 *         &lt;element ref="{}IsAutoApplyingPayments"/>
 *         &lt;element ref="{}PriceLevels" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "defaultShipMethodRef",
    "defaultFOB",
    "defaultMarkup",
    "isTrackingReimbursedExpensesAsIncome",
    "isAutoApplyingPayments",
    "priceLevels"
})
@XmlRootElement(name = "SalesAndCustomersPreferences")
public class SalesAndCustomersPreferences {

    @XmlElement(name = "DefaultShipMethodRef")
    protected DefaultShipMethodRef defaultShipMethodRef;
    @XmlElement(name = "DefaultFOB")
    protected String defaultFOB;
    @XmlElement(name = "DefaultMarkup")
    protected String defaultMarkup;
    @XmlElement(name = "IsTrackingReimbursedExpensesAsIncome", required = true)
    protected String isTrackingReimbursedExpensesAsIncome;
    @XmlElement(name = "IsAutoApplyingPayments", required = true)
    protected String isAutoApplyingPayments;
    @XmlElement(name = "PriceLevels")
    protected PriceLevels priceLevels;

    /**
     * Gets the value of the defaultShipMethodRef property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultShipMethodRef }
     *     
     */
    public DefaultShipMethodRef getDefaultShipMethodRef() {
        return defaultShipMethodRef;
    }

    /**
     * Sets the value of the defaultShipMethodRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultShipMethodRef }
     *     
     */
    public void setDefaultShipMethodRef(DefaultShipMethodRef value) {
        this.defaultShipMethodRef = value;
    }

    /**
     * Gets the value of the defaultFOB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultFOB() {
        return defaultFOB;
    }

    /**
     * Sets the value of the defaultFOB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultFOB(String value) {
        this.defaultFOB = value;
    }

    /**
     * Gets the value of the defaultMarkup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultMarkup() {
        return defaultMarkup;
    }

    /**
     * Sets the value of the defaultMarkup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultMarkup(String value) {
        this.defaultMarkup = value;
    }

    /**
     * Gets the value of the isTrackingReimbursedExpensesAsIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTrackingReimbursedExpensesAsIncome() {
        return isTrackingReimbursedExpensesAsIncome;
    }

    /**
     * Sets the value of the isTrackingReimbursedExpensesAsIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTrackingReimbursedExpensesAsIncome(String value) {
        this.isTrackingReimbursedExpensesAsIncome = value;
    }

    /**
     * Gets the value of the isAutoApplyingPayments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsAutoApplyingPayments() {
        return isAutoApplyingPayments;
    }

    /**
     * Sets the value of the isAutoApplyingPayments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsAutoApplyingPayments(String value) {
        this.isAutoApplyingPayments = value;
    }

    /**
     * Gets the value of the priceLevels property.
     * 
     * @return
     *     possible object is
     *     {@link PriceLevels }
     *     
     */
    public PriceLevels getPriceLevels() {
        return priceLevels;
    }

    /**
     * Sets the value of the priceLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceLevels }
     *     
     */
    public void setPriceLevels(PriceLevels value) {
        this.priceLevels = value;
    }

}
