//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.18 at 07:52:40 PM EDT 
//


package com.alagad.ColdBooks.CA.v110;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="HostQueryRs" type="{}HostQueryRsType"/>
 *         &lt;element name="CompanyQueryRs" type="{}CompanyQueryRsType"/>
 *         &lt;element name="CompanyActivityQueryRs" type="{}CompanyActivityQueryRsType"/>
 *         &lt;element name="PreferencesModRs" type="{}PreferencesModRsType"/>
 *         &lt;element name="PreferencesQueryRs" type="{}PreferencesQueryRsType"/>
 *         &lt;element name="AccountAddRs" type="{}AccountAddRsType"/>
 *         &lt;element name="AccountModRs" type="{}AccountModRsType"/>
 *         &lt;element name="AccountQueryRs" type="{}AccountQueryRsType"/>
 *         &lt;element name="SpecialAccountAddRs" type="{}SpecialAccountAddRsType"/>
 *         &lt;element name="AccountTaxLineInfoQueryRs" type="{}AccountTaxLineInfoQueryRsType"/>
 *         &lt;element name="CustomerAddRs" type="{}CustomerAddRsType"/>
 *         &lt;element name="CustomerModRs" type="{}CustomerModRsType"/>
 *         &lt;element name="CustomerQueryRs" type="{}CustomerQueryRsType"/>
 *         &lt;element name="EmployeeAddRs" type="{}EmployeeAddRsType"/>
 *         &lt;element name="EmployeeModRs" type="{}EmployeeModRsType"/>
 *         &lt;element name="EmployeeQueryRs" type="{}EmployeeQueryRsType"/>
 *         &lt;element name="EmployeeDefaultModRs" type="{}EmployeeDefaultModRsType"/>
 *         &lt;element name="EmployeeDefaultQueryRs" type="{}EmployeeDefaultQueryRsType"/>
 *         &lt;element name="OtherNameAddRs" type="{}OtherNameAddRsType"/>
 *         &lt;element name="OtherNameModRs" type="{}OtherNameModRsType"/>
 *         &lt;element name="OtherNameQueryRs" type="{}OtherNameQueryRsType"/>
 *         &lt;element name="VendorAddRs" type="{}VendorAddRsType"/>
 *         &lt;element name="VendorModRs" type="{}VendorModRsType"/>
 *         &lt;element name="VendorQueryRs" type="{}VendorQueryRsType"/>
 *         &lt;element name="EntityQueryRs" type="{}EntityQueryRsType"/>
 *         &lt;element name="StandardTermsAddRs" type="{}StandardTermsAddRsType"/>
 *         &lt;element name="StandardTermsQueryRs" type="{}StandardTermsQueryRsType"/>
 *         &lt;element name="DateDrivenTermsAddRs" type="{}DateDrivenTermsAddRsType"/>
 *         &lt;element name="DateDrivenTermsQueryRs" type="{}DateDrivenTermsQueryRsType"/>
 *         &lt;element name="TermsQueryRs" type="{}TermsQueryRsType"/>
 *         &lt;element name="ClassAddRs" type="{}ClassAddRsType"/>
 *         &lt;element name="ClassModRs" type="{}ClassModRsType"/>
 *         &lt;element name="ClassQueryRs" type="{}ClassQueryRsType"/>
 *         &lt;element name="SalesRepAddRs" type="{}SalesRepAddRsType"/>
 *         &lt;element name="SalesRepModRs" type="{}SalesRepModRsType"/>
 *         &lt;element name="SalesRepQueryRs" type="{}SalesRepQueryRsType"/>
 *         &lt;element name="CustomerTypeAddRs" type="{}CustomerTypeAddRsType"/>
 *         &lt;element name="CustomerTypeQueryRs" type="{}CustomerTypeQueryRsType"/>
 *         &lt;element name="VendorTypeAddRs" type="{}VendorTypeAddRsType"/>
 *         &lt;element name="VendorTypeQueryRs" type="{}VendorTypeQueryRsType"/>
 *         &lt;element name="JobTypeAddRs" type="{}JobTypeAddRsType"/>
 *         &lt;element name="JobTypeQueryRs" type="{}JobTypeQueryRsType"/>
 *         &lt;element name="CustomerMsgAddRs" type="{}CustomerMsgAddRsType"/>
 *         &lt;element name="CustomerMsgQueryRs" type="{}CustomerMsgQueryRsType"/>
 *         &lt;element name="PaymentMethodAddRs" type="{}PaymentMethodAddRsType"/>
 *         &lt;element name="PaymentMethodQueryRs" type="{}PaymentMethodQueryRsType"/>
 *         &lt;element name="ShipMethodAddRs" type="{}ShipMethodAddRsType"/>
 *         &lt;element name="ShipMethodQueryRs" type="{}ShipMethodQueryRsType"/>
 *         &lt;element name="SalesTaxCodeAddRs" type="{}SalesTaxCodeAddRsType"/>
 *         &lt;element name="SalesTaxCodeModRs" type="{}SalesTaxCodeModRsType"/>
 *         &lt;element name="SalesTaxCodeQueryRs" type="{}SalesTaxCodeQueryRsType"/>
 *         &lt;element name="ToDoAddRs" type="{}ToDoAddRsType"/>
 *         &lt;element name="ToDoModRs" type="{}ToDoModRsType"/>
 *         &lt;element name="ToDoQueryRs" type="{}ToDoQueryRsType"/>
 *         &lt;element name="ItemServiceAddRs" type="{}ItemServiceAddRsType"/>
 *         &lt;element name="ItemServiceModRs" type="{}ItemServiceModRsType"/>
 *         &lt;element name="ItemServiceQueryRs" type="{}ItemServiceQueryRsType"/>
 *         &lt;element name="ItemNonInventoryAddRs" type="{}ItemNonInventoryAddRsType"/>
 *         &lt;element name="ItemNonInventoryModRs" type="{}ItemNonInventoryModRsType"/>
 *         &lt;element name="ItemNonInventoryQueryRs" type="{}ItemNonInventoryQueryRsType"/>
 *         &lt;element name="ItemOtherChargeAddRs" type="{}ItemOtherChargeAddRsType"/>
 *         &lt;element name="ItemOtherChargeModRs" type="{}ItemOtherChargeModRsType"/>
 *         &lt;element name="ItemOtherChargeQueryRs" type="{}ItemOtherChargeQueryRsType"/>
 *         &lt;element name="ItemInventoryAddRs" type="{}ItemInventoryAddRsType"/>
 *         &lt;element name="ItemInventoryModRs" type="{}ItemInventoryModRsType"/>
 *         &lt;element name="ItemInventoryQueryRs" type="{}ItemInventoryQueryRsType"/>
 *         &lt;element name="ItemInventoryAssemblyAddRs" type="{}ItemInventoryAssemblyAddRsType"/>
 *         &lt;element name="ItemInventoryAssemblyModRs" type="{}ItemInventoryAssemblyModRsType"/>
 *         &lt;element name="ItemInventoryAssemblyQueryRs" type="{}ItemInventoryAssemblyQueryRsType"/>
 *         &lt;element name="ItemFixedAssetAddRs" type="{}ItemFixedAssetAddRsType"/>
 *         &lt;element name="ItemFixedAssetModRs" type="{}ItemFixedAssetModRsType"/>
 *         &lt;element name="ItemFixedAssetQueryRs" type="{}ItemFixedAssetQueryRsType"/>
 *         &lt;element name="ItemSubtotalAddRs" type="{}ItemSubtotalAddRsType"/>
 *         &lt;element name="ItemSubtotalModRs" type="{}ItemSubtotalModRsType"/>
 *         &lt;element name="ItemSubtotalQueryRs" type="{}ItemSubtotalQueryRsType"/>
 *         &lt;element name="ItemDiscountAddRs" type="{}ItemDiscountAddRsType"/>
 *         &lt;element name="ItemDiscountModRs" type="{}ItemDiscountModRsType"/>
 *         &lt;element name="ItemDiscountQueryRs" type="{}ItemDiscountQueryRsType"/>
 *         &lt;element name="ItemPaymentAddRs" type="{}ItemPaymentAddRsType"/>
 *         &lt;element name="ItemPaymentModRs" type="{}ItemPaymentModRsType"/>
 *         &lt;element name="ItemPaymentQueryRs" type="{}ItemPaymentQueryRsType"/>
 *         &lt;element name="ItemSalesTaxAddRs" type="{}ItemSalesTaxAddRsType"/>
 *         &lt;element name="ItemSalesTaxModRs" type="{}ItemSalesTaxModRsType"/>
 *         &lt;element name="ItemSalesTaxQueryRs" type="{}ItemSalesTaxQueryRsType"/>
 *         &lt;element name="ItemSalesTaxGroupAddRs" type="{}ItemSalesTaxGroupAddRsType"/>
 *         &lt;element name="ItemSalesTaxGroupModRs" type="{}ItemSalesTaxGroupModRsType"/>
 *         &lt;element name="ItemSalesTaxGroupQueryRs" type="{}ItemSalesTaxGroupQueryRsType"/>
 *         &lt;element name="ItemGroupAddRs" type="{}ItemGroupAddRsType"/>
 *         &lt;element name="ItemGroupModRs" type="{}ItemGroupModRsType"/>
 *         &lt;element name="ItemGroupQueryRs" type="{}ItemGroupQueryRsType"/>
 *         &lt;element name="SpecialItemAddRs" type="{}SpecialItemAddRsType"/>
 *         &lt;element name="ItemQueryRs" type="{}ItemQueryRsType"/>
 *         &lt;element name="PayrollItemWageAddRs" type="{}PayrollItemWageAddRsType"/>
 *         &lt;element name="PayrollItemWageModRs" type="{}PayrollItemWageModRsType"/>
 *         &lt;element name="PayrollItemWageQueryRs" type="{}PayrollItemWageQueryRsType"/>
 *         &lt;element name="PayrollItemNonWageQueryRs" type="{}PayrollItemNonWageQueryRsType"/>
 *         &lt;element name="PayrollItemAdditionAddRs" type="{}PayrollItemAdditionAddRsType"/>
 *         &lt;element name="PayrollItemAdditionModRs" type="{}PayrollItemAdditionModRsType"/>
 *         &lt;element name="PayrollItemDeductionAddRs" type="{}PayrollItemDeductionAddRsType"/>
 *         &lt;element name="PayrollItemDeductionModRs" type="{}PayrollItemDeductionModRsType"/>
 *         &lt;element name="PayrollItemCompanyContributionAddRs" type="{}PayrollItemCompanyContributionAddRsType"/>
 *         &lt;element name="PayrollItemCompanyContributionModRs" type="{}PayrollItemCompanyContributionModRsType"/>
 *         &lt;element name="PayrollItemWorkersCompensationAddRs" type="{}PayrollItemWorkersCompensationAddRsType"/>
 *         &lt;element name="PayrollItemWorkersCompensationModRs" type="{}PayrollItemWorkersCompensationModRsType"/>
 *         &lt;element name="PayrollItemDirectDepositAddRs" type="{}PayrollItemDirectDepositAddRsType"/>
 *         &lt;element name="PayrollItemDirectDepositModRs" type="{}PayrollItemDirectDepositModRsType"/>
 *         &lt;element name="PayrollItemTaxAddRs" type="{}PayrollItemTaxAddRsType"/>
 *         &lt;element name="PayrollItemTaxModRs" type="{}PayrollItemTaxModRsType"/>
 *         &lt;element name="PayrollItemQueryRs" type="{}PayrollItemQueryRsType"/>
 *         &lt;element name="TemplateQueryRs" type="{}TemplateQueryRsType"/>
 *         &lt;element name="PriceLevelAddRs" type="{}PriceLevelAddRsType"/>
 *         &lt;element name="PriceLevelModRs" type="{}PriceLevelModRsType"/>
 *         &lt;element name="PriceLevelQueryRs" type="{}PriceLevelQueryRsType"/>
 *         &lt;element name="BillingRateAddRs" type="{}BillingRateAddRsType"/>
 *         &lt;element name="BillingRateQueryRs" type="{}BillingRateQueryRsType"/>
 *         &lt;element name="VehicleAddRs" type="{}VehicleAddRsType"/>
 *         &lt;element name="VehicleModRs" type="{}VehicleModRsType"/>
 *         &lt;element name="VehicleQueryRs" type="{}VehicleQueryRsType"/>
 *         &lt;element name="UnitOfMeasureSetAddRs" type="{}UnitOfMeasureSetAddRsType"/>
 *         &lt;element name="UnitOfMeasureSetQueryRs" type="{}UnitOfMeasureSetQueryRsType"/>
 *         &lt;element name="WorkersCompCodeAddRs" type="{}WorkersCompCodeAddRsType"/>
 *         &lt;element name="WorkersCompCodeModRs" type="{}WorkersCompCodeModRsType"/>
 *         &lt;element name="WorkersCompCodeQueryRs" type="{}WorkersCompCodeQueryRsType"/>
 *         &lt;element name="Form1099CategoryAccountMappingModRs" type="{}Form1099CategoryAccountMappingModRsType"/>
 *         &lt;element name="Form1099CategoryAccountMappingQueryRs" type="{}Form1099CategoryAccountMappingQueryRsType"/>
 *         &lt;element name="SalesTaxReturnQueryRs" type="{}SalesTaxReturnQueryRsType"/>
 *         &lt;element name="SalesTaxReturnLineQueryRs" type="{}SalesTaxReturnLineQueryRsType"/>
 *         &lt;element name="CurrencyAddRs" type="{}CurrencyAddRsType"/>
 *         &lt;element name="CurrencyModRs" type="{}CurrencyModRsType"/>
 *         &lt;element name="CurrencyQueryRs" type="{}CurrencyQueryRsType"/>
 *         &lt;element name="PayrollLastPeriodQueryRs" type="{}PayrollLastPeriodQueryRsType"/>
 *         &lt;element name="InventorySiteAddRs" type="{}InventorySiteAddRsType"/>
 *         &lt;element name="InventorySiteModRs" type="{}InventorySiteModRsType"/>
 *         &lt;element name="InventorySiteQueryRs" type="{}InventorySiteQueryRsType"/>
 *         &lt;element name="InvoiceAddRs" type="{}InvoiceAddRsType"/>
 *         &lt;element name="InvoiceModRs" type="{}InvoiceModRsType"/>
 *         &lt;element name="InvoiceQueryRs" type="{}InvoiceQueryRsType"/>
 *         &lt;element name="EstimateAddRs" type="{}EstimateAddRsType"/>
 *         &lt;element name="EstimateModRs" type="{}EstimateModRsType"/>
 *         &lt;element name="EstimateQueryRs" type="{}EstimateQueryRsType"/>
 *         &lt;element name="SalesOrderAddRs" type="{}SalesOrderAddRsType"/>
 *         &lt;element name="SalesOrderModRs" type="{}SalesOrderModRsType"/>
 *         &lt;element name="SalesOrderQueryRs" type="{}SalesOrderQueryRsType"/>
 *         &lt;element name="SalesReceiptAddRs" type="{}SalesReceiptAddRsType"/>
 *         &lt;element name="SalesReceiptModRs" type="{}SalesReceiptModRsType"/>
 *         &lt;element name="SalesReceiptQueryRs" type="{}SalesReceiptQueryRsType"/>
 *         &lt;element name="CreditMemoAddRs" type="{}CreditMemoAddRsType"/>
 *         &lt;element name="CreditMemoModRs" type="{}CreditMemoModRsType"/>
 *         &lt;element name="CreditMemoQueryRs" type="{}CreditMemoQueryRsType"/>
 *         &lt;element name="ReceivePaymentAddRs" type="{}ReceivePaymentAddRsType"/>
 *         &lt;element name="ReceivePaymentModRs" type="{}ReceivePaymentModRsType"/>
 *         &lt;element name="ReceivePaymentQueryRs" type="{}ReceivePaymentQueryRsType"/>
 *         &lt;element name="ReceivePaymentToDepositQueryRs" type="{}ReceivePaymentToDepositQueryRsType"/>
 *         &lt;element name="ChargeAddRs" type="{}ChargeAddRsType"/>
 *         &lt;element name="ChargeModRs" type="{}ChargeModRsType"/>
 *         &lt;element name="ChargeQueryRs" type="{}ChargeQueryRsType"/>
 *         &lt;element name="PurchaseOrderAddRs" type="{}PurchaseOrderAddRsType"/>
 *         &lt;element name="PurchaseOrderModRs" type="{}PurchaseOrderModRsType"/>
 *         &lt;element name="PurchaseOrderQueryRs" type="{}PurchaseOrderQueryRsType"/>
 *         &lt;element name="BillAddRs" type="{}BillAddRsType"/>
 *         &lt;element name="BillModRs" type="{}BillModRsType"/>
 *         &lt;element name="BillQueryRs" type="{}BillQueryRsType"/>
 *         &lt;element name="ItemReceiptAddRs" type="{}ItemReceiptAddRsType"/>
 *         &lt;element name="ItemReceiptModRs" type="{}ItemReceiptModRsType"/>
 *         &lt;element name="ItemReceiptQueryRs" type="{}ItemReceiptQueryRsType"/>
 *         &lt;element name="VendorCreditAddRs" type="{}VendorCreditAddRsType"/>
 *         &lt;element name="VendorCreditModRs" type="{}VendorCreditModRsType"/>
 *         &lt;element name="VendorCreditQueryRs" type="{}VendorCreditQueryRsType"/>
 *         &lt;element name="BillPaymentCheckAddRs" type="{}BillPaymentCheckAddRsType"/>
 *         &lt;element name="BillPaymentCheckModRs" type="{}BillPaymentCheckModRsType"/>
 *         &lt;element name="BillPaymentCheckQueryRs" type="{}BillPaymentCheckQueryRsType"/>
 *         &lt;element name="BillPaymentCreditCardAddRs" type="{}BillPaymentCreditCardAddRsType"/>
 *         &lt;element name="BillPaymentCreditCardQueryRs" type="{}BillPaymentCreditCardQueryRsType"/>
 *         &lt;element name="BillToPayQueryRs" type="{}BillToPayQueryRsType"/>
 *         &lt;element name="SalesTaxPaymentCheckAddRs" type="{}SalesTaxPaymentCheckAddRsType"/>
 *         &lt;element name="SalesTaxPaymentCheckModRs" type="{}SalesTaxPaymentCheckModRsType"/>
 *         &lt;element name="SalesTaxPaymentCheckQueryRs" type="{}SalesTaxPaymentCheckQueryRsType"/>
 *         &lt;element name="SalesTaxPayableQueryRs" type="{}SalesTaxPayableQueryRsType"/>
 *         &lt;element name="InventoryAdjustmentAddRs" type="{}InventoryAdjustmentAddRsType"/>
 *         &lt;element name="InventoryAdjustmentModRs" type="{}InventoryAdjustmentModRsType"/>
 *         &lt;element name="InventoryAdjustmentQueryRs" type="{}InventoryAdjustmentQueryRsType"/>
 *         &lt;element name="TimeTrackingAddRs" type="{}TimeTrackingAddRsType"/>
 *         &lt;element name="TimeTrackingModRs" type="{}TimeTrackingModRsType"/>
 *         &lt;element name="TimeTrackingQueryRs" type="{}TimeTrackingQueryRsType"/>
 *         &lt;element name="CheckAddRs" type="{}CheckAddRsType"/>
 *         &lt;element name="CheckModRs" type="{}CheckModRsType"/>
 *         &lt;element name="CheckQueryRs" type="{}CheckQueryRsType"/>
 *         &lt;element name="CreditCardChargeAddRs" type="{}CreditCardChargeAddRsType"/>
 *         &lt;element name="CreditCardChargeModRs" type="{}CreditCardChargeModRsType"/>
 *         &lt;element name="CreditCardChargeQueryRs" type="{}CreditCardChargeQueryRsType"/>
 *         &lt;element name="CreditCardCreditAddRs" type="{}CreditCardCreditAddRsType"/>
 *         &lt;element name="CreditCardCreditModRs" type="{}CreditCardCreditModRsType"/>
 *         &lt;element name="CreditCardCreditQueryRs" type="{}CreditCardCreditQueryRsType"/>
 *         &lt;element name="JournalEntryAddRs" type="{}JournalEntryAddRsType"/>
 *         &lt;element name="JournalEntryModRs" type="{}JournalEntryModRsType"/>
 *         &lt;element name="JournalEntryQueryRs" type="{}JournalEntryQueryRsType"/>
 *         &lt;element name="DepositAddRs" type="{}DepositAddRsType"/>
 *         &lt;element name="DepositModRs" type="{}DepositModRsType"/>
 *         &lt;element name="DepositQueryRs" type="{}DepositQueryRsType"/>
 *         &lt;element name="ListDelRs" type="{}ListDelRsType"/>
 *         &lt;element name="ListMergeRs" type="{}ListMergeRsType"/>
 *         &lt;element name="ListDeletedQueryRs" type="{}ListDeletedQueryRsType"/>
 *         &lt;element name="TxnDelRs" type="{}TxnDelRsType"/>
 *         &lt;element name="TxnVoidRs" type="{}TxnVoidRsType"/>
 *         &lt;element name="TxnDeletedQueryRs" type="{}TxnDeletedQueryRsType"/>
 *         &lt;element name="ClearedStatusModRs" type="{}ClearedStatusModRsType"/>
 *         &lt;element name="ListDisplayAddRs" type="{}ListDisplayAddRsType"/>
 *         &lt;element name="ListDisplayModRs" type="{}ListDisplayModRsType"/>
 *         &lt;element name="TxnDisplayAddRs" type="{}TxnDisplayAddRsType"/>
 *         &lt;element name="TxnDisplayModRs" type="{}TxnDisplayModRsType"/>
 *         &lt;element name="AlertAddRs" type="{}AlertAddRsType"/>
 *         &lt;element name="AlertDelRs" type="{}AlertDelRsType"/>
 *         &lt;element name="AlertQueryRs" type="{}AlertQueryRsType"/>
 *         &lt;element name="DataEventRecoveryInfoDelRs" type="{}DataEventRecoveryInfoDelRsType"/>
 *         &lt;element name="DataEventRecoveryInfoQueryRs" type="{}DataEventRecoveryInfoQueryRsType"/>
 *         &lt;element name="TransactionQueryRs" type="{}TransactionQueryRsType"/>
 *         &lt;element name="BuildAssemblyAddRs" type="{}BuildAssemblyAddRsType"/>
 *         &lt;element name="BuildAssemblyModRs" type="{}BuildAssemblyModRsType"/>
 *         &lt;element name="BuildAssemblyQueryRs" type="{}BuildAssemblyQueryRsType"/>
 *         &lt;element name="ItemAssembliesCanBuildQueryRs" type="{}ItemAssembliesCanBuildQueryRsType"/>
 *         &lt;element name="ARRefundCreditCardAddRs" type="{}ARRefundCreditCardAddRsType"/>
 *         &lt;element name="ARRefundCreditCardQueryRs" type="{}ARRefundCreditCardQueryRsType"/>
 *         &lt;element name="VehicleMileageAddRs" type="{}VehicleMileageAddRsType"/>
 *         &lt;element name="VehicleMileageQueryRs" type="{}VehicleMileageQueryRsType"/>
 *         &lt;element name="PayrollYearToDateAdjustmentAddRs" type="{}PayrollYearToDateAdjustmentAddRsType"/>
 *         &lt;element name="PayrollYearToDateAdjustmentQueryRs" type="{}PayrollYearToDateAdjustmentQueryRsType"/>
 *         &lt;element name="PayrollLiabilityAdjustmentAddRs" type="{}PayrollLiabilityAdjustmentAddRsType"/>
 *         &lt;element name="PayrollLiabilityAdjustmentQueryRs" type="{}PayrollLiabilityAdjustmentQueryRsType"/>
 *         &lt;element name="PayrollPriorPaymentAddRs" type="{}PayrollPriorPaymentAddRsType"/>
 *         &lt;element name="PayrollPriorPaymentQueryRs" type="{}PayrollPriorPaymentQueryRsType"/>
 *         &lt;element name="PaycheckQueryRs" type="{}PaycheckQueryRsType"/>
 *         &lt;element name="PayrollLiabilityCheckQueryRs" type="{}PayrollLiabilityCheckQueryRsType"/>
 *         &lt;element name="TransferInventoryAddRs" type="{}TransferInventoryAddRsType"/>
 *         &lt;element name="TransferInventoryModRs" type="{}TransferInventoryModRsType"/>
 *         &lt;element name="TransferInventoryQueryRs" type="{}TransferInventoryQueryRsType"/>
 *         &lt;element name="ItemSitesQueryRs" type="{}ItemSitesQueryRsType"/>
 *         &lt;element name="QBCommandExecRs" type="{}QBCommandExecRsType"/>
 *         &lt;element name="GeneralSummaryReportQueryRs" type="{}GeneralSummaryReportQueryRsType"/>
 *         &lt;element name="JobReportQueryRs" type="{}JobReportQueryRsType"/>
 *         &lt;element name="TimeReportQueryRs" type="{}TimeReportQueryRsType"/>
 *         &lt;element name="AgingReportQueryRs" type="{}AgingReportQueryRsType"/>
 *         &lt;element name="BudgetSummaryReportQueryRs" type="{}BudgetSummaryReportQueryRsType"/>
 *         &lt;element name="GeneralDetailReportQueryRs" type="{}GeneralDetailReportQueryRsType"/>
 *         &lt;element name="CustomDetailReportQueryRs" type="{}CustomDetailReportQueryRsType"/>
 *         &lt;element name="CustomSummaryReportQueryRs" type="{}CustomSummaryReportQueryRsType"/>
 *         &lt;element name="PayrollDetailReportQueryRs" type="{}PayrollDetailReportQueryRsType"/>
 *         &lt;element name="PayrollSummaryReportQueryRs" type="{}PayrollSummaryReportQueryRsType"/>
 *         &lt;element name="DataExtDefAddRs" type="{}DataExtDefAddRsType"/>
 *         &lt;element name="DataExtDefModRs" type="{}DataExtDefModRsType"/>
 *         &lt;element name="DataExtDefDelRs" type="{}DataExtDefDelRsType"/>
 *         &lt;element name="DataExtDefQueryRs" type="{}DataExtDefQueryRsType"/>
 *         &lt;element name="DataExtAddRs" type="{}DataExtAddRsType"/>
 *         &lt;element name="DataExtModRs" type="{}DataExtModRsType"/>
 *         &lt;element name="DataExtDelRs" type="{}DataExtDelRsType"/>
 *       &lt;/choice>
 *       &lt;attribute name="newMessageSetID" type="{}STRTYPE" />
 *       &lt;attribute name="messageSetStatusCode" type="{}INTTYPE" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs"
})
@XmlRootElement(name = "QBXMLMsgsRs")
public class QBXMLMsgsRs {

    @XmlElements({
        @XmlElement(name = "ItemReceiptAddRs", type = ItemReceiptAddRsType.class),
        @XmlElement(name = "CreditCardChargeQueryRs", type = CreditCardChargeQueryRsType.class),
        @XmlElement(name = "ItemPaymentAddRs", type = ItemPaymentAddRsType.class),
        @XmlElement(name = "AgingReportQueryRs", type = AgingReportQueryRsType.class),
        @XmlElement(name = "PayrollYearToDateAdjustmentQueryRs", type = PayrollYearToDateAdjustmentQueryRsType.class),
        @XmlElement(name = "BuildAssemblyModRs", type = BuildAssemblyModRsType.class),
        @XmlElement(name = "OtherNameAddRs", type = OtherNameAddRsType.class),
        @XmlElement(name = "SalesOrderAddRs", type = SalesOrderAddRsType.class),
        @XmlElement(name = "CreditCardChargeAddRs", type = CreditCardChargeAddRsType.class),
        @XmlElement(name = "SalesTaxCodeAddRs", type = SalesTaxCodeAddRsType.class),
        @XmlElement(name = "PriceLevelQueryRs", type = PriceLevelQueryRsType.class),
        @XmlElement(name = "VehicleModRs", type = VehicleModRsType.class),
        @XmlElement(name = "InvoiceQueryRs", type = InvoiceQueryRsType.class),
        @XmlElement(name = "CustomerMsgAddRs", type = CustomerMsgAddRsType.class),
        @XmlElement(name = "CurrencyQueryRs", type = CurrencyQueryRsType.class),
        @XmlElement(name = "SalesReceiptAddRs", type = SalesReceiptAddRsType.class),
        @XmlElement(name = "PayrollLiabilityAdjustmentQueryRs", type = PayrollLiabilityAdjustmentQueryRsType.class),
        @XmlElement(name = "ReceivePaymentQueryRs", type = ReceivePaymentQueryRsType.class),
        @XmlElement(name = "PriceLevelModRs", type = PriceLevelModRsType.class),
        @XmlElement(name = "StandardTermsAddRs", type = StandardTermsAddRsType.class),
        @XmlElement(name = "PayrollItemAdditionModRs", type = PayrollItemAdditionModRsType.class),
        @XmlElement(name = "PaycheckQueryRs", type = PaycheckQueryRsType.class),
        @XmlElement(name = "InventoryAdjustmentModRs", type = InventoryAdjustmentModRsType.class),
        @XmlElement(name = "EmployeeDefaultModRs", type = EmployeeDefaultModRsType.class),
        @XmlElement(name = "VehicleQueryRs", type = VehicleQueryRsType.class),
        @XmlElement(name = "TimeTrackingAddRs", type = TimeTrackingAddRsType.class),
        @XmlElement(name = "DateDrivenTermsQueryRs", type = DateDrivenTermsQueryRsType.class),
        @XmlElement(name = "JobTypeAddRs", type = JobTypeAddRsType.class),
        @XmlElement(name = "ItemServiceQueryRs", type = ItemServiceQueryRsType.class),
        @XmlElement(name = "JobTypeQueryRs", type = JobTypeQueryRsType.class),
        @XmlElement(name = "ReceivePaymentAddRs", type = ReceivePaymentAddRsType.class),
        @XmlElement(name = "ListDelRs", type = ListDelRsType.class),
        @XmlElement(name = "EmployeeModRs", type = EmployeeModRsType.class),
        @XmlElement(name = "ItemFixedAssetModRs", type = ItemFixedAssetModRsType.class),
        @XmlElement(name = "DataExtAddRs", type = DataExtAddRsType.class),
        @XmlElement(name = "ItemSubtotalQueryRs", type = ItemSubtotalQueryRsType.class),
        @XmlElement(name = "EmployeeAddRs", type = EmployeeAddRsType.class),
        @XmlElement(name = "PayrollItemDeductionAddRs", type = PayrollItemDeductionAddRsType.class),
        @XmlElement(name = "PayrollPriorPaymentAddRs", type = PayrollPriorPaymentAddRsType.class),
        @XmlElement(name = "UnitOfMeasureSetAddRs", type = UnitOfMeasureSetAddRsType.class),
        @XmlElement(name = "AccountQueryRs", type = AccountQueryRsType.class),
        @XmlElement(name = "ItemGroupAddRs", type = ItemGroupAddRsType.class),
        @XmlElement(name = "ItemInventoryQueryRs", type = ItemInventoryQueryRsType.class),
        @XmlElement(name = "ItemNonInventoryAddRs", type = ItemNonInventoryAddRsType.class),
        @XmlElement(name = "TermsQueryRs", type = TermsQueryRsType.class),
        @XmlElement(name = "ChargeModRs", type = ChargeModRsType.class),
        @XmlElement(name = "BillingRateAddRs", type = BillingRateAddRsType.class),
        @XmlElement(name = "CustomerTypeQueryRs", type = CustomerTypeQueryRsType.class),
        @XmlElement(name = "VehicleMileageQueryRs", type = VehicleMileageQueryRsType.class),
        @XmlElement(name = "ItemSitesQueryRs", type = ItemSitesQueryRsType.class),
        @XmlElement(name = "BillQueryRs", type = BillQueryRsType.class),
        @XmlElement(name = "ItemDiscountQueryRs", type = ItemDiscountQueryRsType.class),
        @XmlElement(name = "SalesTaxCodeQueryRs", type = SalesTaxCodeQueryRsType.class),
        @XmlElement(name = "TimeTrackingQueryRs", type = TimeTrackingQueryRsType.class),
        @XmlElement(name = "ItemSalesTaxAddRs", type = ItemSalesTaxAddRsType.class),
        @XmlElement(name = "PurchaseOrderModRs", type = PurchaseOrderModRsType.class),
        @XmlElement(name = "CustomerQueryRs", type = CustomerQueryRsType.class),
        @XmlElement(name = "WorkersCompCodeModRs", type = WorkersCompCodeModRsType.class),
        @XmlElement(name = "ItemSubtotalAddRs", type = ItemSubtotalAddRsType.class),
        @XmlElement(name = "ItemSubtotalModRs", type = ItemSubtotalModRsType.class),
        @XmlElement(name = "CompanyActivityQueryRs", type = CompanyActivityQueryRsType.class),
        @XmlElement(name = "AccountModRs", type = AccountModRsType.class),
        @XmlElement(name = "AlertDelRs", type = AlertDelRsType.class),
        @XmlElement(name = "VendorAddRs", type = VendorAddRsType.class),
        @XmlElement(name = "PayrollLiabilityAdjustmentAddRs", type = PayrollLiabilityAdjustmentAddRsType.class),
        @XmlElement(name = "DataEventRecoveryInfoQueryRs", type = DataEventRecoveryInfoQueryRsType.class),
        @XmlElement(name = "CreditCardCreditQueryRs", type = CreditCardCreditQueryRsType.class),
        @XmlElement(name = "CheckQueryRs", type = CheckQueryRsType.class),
        @XmlElement(name = "ItemFixedAssetAddRs", type = ItemFixedAssetAddRsType.class),
        @XmlElement(name = "AccountAddRs", type = AccountAddRsType.class),
        @XmlElement(name = "GeneralSummaryReportQueryRs", type = GeneralSummaryReportQueryRsType.class),
        @XmlElement(name = "DataEventRecoveryInfoDelRs", type = DataEventRecoveryInfoDelRsType.class),
        @XmlElement(name = "DepositAddRs", type = DepositAddRsType.class),
        @XmlElement(name = "TimeTrackingModRs", type = TimeTrackingModRsType.class),
        @XmlElement(name = "SalesRepAddRs", type = SalesRepAddRsType.class),
        @XmlElement(name = "DataExtDelRs", type = DataExtDelRsType.class),
        @XmlElement(name = "PayrollLiabilityCheckQueryRs", type = PayrollLiabilityCheckQueryRsType.class),
        @XmlElement(name = "PayrollItemWageAddRs", type = PayrollItemWageAddRsType.class),
        @XmlElement(name = "HostQueryRs", type = HostQueryRsType.class),
        @XmlElement(name = "CompanyQueryRs", type = CompanyQueryRsType.class),
        @XmlElement(name = "DataExtDefDelRs", type = DataExtDefDelRsType.class),
        @XmlElement(name = "ClassModRs", type = ClassModRsType.class),
        @XmlElement(name = "VendorCreditAddRs", type = VendorCreditAddRsType.class),
        @XmlElement(name = "TransferInventoryQueryRs", type = TransferInventoryQueryRsType.class),
        @XmlElement(name = "VendorTypeQueryRs", type = VendorTypeQueryRsType.class),
        @XmlElement(name = "VendorTypeAddRs", type = VendorTypeAddRsType.class),
        @XmlElement(name = "DataExtDefQueryRs", type = DataExtDefQueryRsType.class),
        @XmlElement(name = "CustomerTypeAddRs", type = CustomerTypeAddRsType.class),
        @XmlElement(name = "ListDeletedQueryRs", type = ListDeletedQueryRsType.class),
        @XmlElement(name = "PreferencesModRs", type = PreferencesModRsType.class),
        @XmlElement(name = "ARRefundCreditCardAddRs", type = ARRefundCreditCardAddRsType.class),
        @XmlElement(name = "BillPaymentCreditCardQueryRs", type = BillPaymentCreditCardQueryRsType.class),
        @XmlElement(name = "ShipMethodAddRs", type = ShipMethodAddRsType.class),
        @XmlElement(name = "PayrollYearToDateAdjustmentAddRs", type = PayrollYearToDateAdjustmentAddRsType.class),
        @XmlElement(name = "ItemDiscountModRs", type = ItemDiscountModRsType.class),
        @XmlElement(name = "ListMergeRs", type = ListMergeRsType.class),
        @XmlElement(name = "PayrollItemWorkersCompensationModRs", type = PayrollItemWorkersCompensationModRsType.class),
        @XmlElement(name = "PurchaseOrderAddRs", type = PurchaseOrderAddRsType.class),
        @XmlElement(name = "InventorySiteAddRs", type = InventorySiteAddRsType.class),
        @XmlElement(name = "TransactionQueryRs", type = TransactionQueryRsType.class),
        @XmlElement(name = "SpecialItemAddRs", type = SpecialItemAddRsType.class),
        @XmlElement(name = "AlertQueryRs", type = AlertQueryRsType.class),
        @XmlElement(name = "SalesTaxPaymentCheckModRs", type = SalesTaxPaymentCheckModRsType.class),
        @XmlElement(name = "EmployeeDefaultQueryRs", type = EmployeeDefaultQueryRsType.class),
        @XmlElement(name = "PayrollItemCompanyContributionAddRs", type = PayrollItemCompanyContributionAddRsType.class),
        @XmlElement(name = "EstimateAddRs", type = EstimateAddRsType.class),
        @XmlElement(name = "ClassQueryRs", type = ClassQueryRsType.class),
        @XmlElement(name = "CustomerModRs", type = CustomerModRsType.class),
        @XmlElement(name = "PayrollItemDirectDepositModRs", type = PayrollItemDirectDepositModRsType.class),
        @XmlElement(name = "ItemServiceModRs", type = ItemServiceModRsType.class),
        @XmlElement(name = "OtherNameQueryRs", type = OtherNameQueryRsType.class),
        @XmlElement(name = "PayrollDetailReportQueryRs", type = PayrollDetailReportQueryRsType.class),
        @XmlElement(name = "ItemPaymentModRs", type = ItemPaymentModRsType.class),
        @XmlElement(name = "BillToPayQueryRs", type = BillToPayQueryRsType.class),
        @XmlElement(name = "PayrollItemTaxModRs", type = PayrollItemTaxModRsType.class),
        @XmlElement(name = "TxnDisplayAddRs", type = TxnDisplayAddRsType.class),
        @XmlElement(name = "CurrencyModRs", type = CurrencyModRsType.class),
        @XmlElement(name = "SalesTaxPaymentCheckAddRs", type = SalesTaxPaymentCheckAddRsType.class),
        @XmlElement(name = "BillPaymentCheckQueryRs", type = BillPaymentCheckQueryRsType.class),
        @XmlElement(name = "TxnDeletedQueryRs", type = TxnDeletedQueryRsType.class),
        @XmlElement(name = "QBCommandExecRs", type = QBCommandExecRsType.class),
        @XmlElement(name = "VehicleAddRs", type = VehicleAddRsType.class),
        @XmlElement(name = "PayrollItemAdditionAddRs", type = PayrollItemAdditionAddRsType.class),
        @XmlElement(name = "ChargeAddRs", type = ChargeAddRsType.class),
        @XmlElement(name = "DepositQueryRs", type = DepositQueryRsType.class),
        @XmlElement(name = "WorkersCompCodeAddRs", type = WorkersCompCodeAddRsType.class),
        @XmlElement(name = "VendorModRs", type = VendorModRsType.class),
        @XmlElement(name = "BillModRs", type = BillModRsType.class),
        @XmlElement(name = "EstimateQueryRs", type = EstimateQueryRsType.class),
        @XmlElement(name = "CreditCardCreditAddRs", type = CreditCardCreditAddRsType.class),
        @XmlElement(name = "ClassAddRs", type = ClassAddRsType.class),
        @XmlElement(name = "PaymentMethodAddRs", type = PaymentMethodAddRsType.class),
        @XmlElement(name = "InventorySiteModRs", type = InventorySiteModRsType.class),
        @XmlElement(name = "ItemReceiptQueryRs", type = ItemReceiptQueryRsType.class),
        @XmlElement(name = "ItemQueryRs", type = ItemQueryRsType.class),
        @XmlElement(name = "ChargeQueryRs", type = ChargeQueryRsType.class),
        @XmlElement(name = "ItemNonInventoryQueryRs", type = ItemNonInventoryQueryRsType.class),
        @XmlElement(name = "ItemOtherChargeModRs", type = ItemOtherChargeModRsType.class),
        @XmlElement(name = "JobReportQueryRs", type = JobReportQueryRsType.class),
        @XmlElement(name = "PreferencesQueryRs", type = PreferencesQueryRsType.class),
        @XmlElement(name = "TxnDisplayModRs", type = TxnDisplayModRsType.class),
        @XmlElement(name = "ItemOtherChargeAddRs", type = ItemOtherChargeAddRsType.class),
        @XmlElement(name = "AccountTaxLineInfoQueryRs", type = AccountTaxLineInfoQueryRsType.class),
        @XmlElement(name = "InventorySiteQueryRs", type = InventorySiteQueryRsType.class),
        @XmlElement(name = "PayrollSummaryReportQueryRs", type = PayrollSummaryReportQueryRsType.class),
        @XmlElement(name = "SalesTaxCodeModRs", type = SalesTaxCodeModRsType.class),
        @XmlElement(name = "SalesTaxReturnLineQueryRs", type = SalesTaxReturnLineQueryRsType.class),
        @XmlElement(name = "DepositModRs", type = DepositModRsType.class),
        @XmlElement(name = "ItemInventoryAddRs", type = ItemInventoryAddRsType.class),
        @XmlElement(name = "CurrencyAddRs", type = CurrencyAddRsType.class),
        @XmlElement(name = "ItemReceiptModRs", type = ItemReceiptModRsType.class),
        @XmlElement(name = "VendorCreditModRs", type = VendorCreditModRsType.class),
        @XmlElement(name = "CheckAddRs", type = CheckAddRsType.class),
        @XmlElement(name = "Form1099CategoryAccountMappingQueryRs", type = Form1099CategoryAccountMappingQueryRsType.class),
        @XmlElement(name = "ItemGroupModRs", type = ItemGroupModRsType.class),
        @XmlElement(name = "SalesOrderModRs", type = SalesOrderModRsType.class),
        @XmlElement(name = "PayrollItemCompanyContributionModRs", type = PayrollItemCompanyContributionModRsType.class),
        @XmlElement(name = "DateDrivenTermsAddRs", type = DateDrivenTermsAddRsType.class),
        @XmlElement(name = "CreditCardChargeModRs", type = CreditCardChargeModRsType.class),
        @XmlElement(name = "PayrollPriorPaymentQueryRs", type = PayrollPriorPaymentQueryRsType.class),
        @XmlElement(name = "SalesReceiptQueryRs", type = SalesReceiptQueryRsType.class),
        @XmlElement(name = "EmployeeQueryRs", type = EmployeeQueryRsType.class),
        @XmlElement(name = "ARRefundCreditCardQueryRs", type = ARRefundCreditCardQueryRsType.class),
        @XmlElement(name = "ToDoAddRs", type = ToDoAddRsType.class),
        @XmlElement(name = "VehicleMileageAddRs", type = VehicleMileageAddRsType.class),
        @XmlElement(name = "ItemSalesTaxGroupModRs", type = ItemSalesTaxGroupModRsType.class),
        @XmlElement(name = "SalesTaxPaymentCheckQueryRs", type = SalesTaxPaymentCheckQueryRsType.class),
        @XmlElement(name = "PayrollItemWorkersCompensationAddRs", type = PayrollItemWorkersCompensationAddRsType.class),
        @XmlElement(name = "InventoryAdjustmentQueryRs", type = InventoryAdjustmentQueryRsType.class),
        @XmlElement(name = "VendorQueryRs", type = VendorQueryRsType.class),
        @XmlElement(name = "ItemInventoryAssemblyAddRs", type = ItemInventoryAssemblyAddRsType.class),
        @XmlElement(name = "PayrollItemDeductionModRs", type = PayrollItemDeductionModRsType.class),
        @XmlElement(name = "PayrollLastPeriodQueryRs", type = PayrollLastPeriodQueryRsType.class),
        @XmlElement(name = "ItemOtherChargeQueryRs", type = ItemOtherChargeQueryRsType.class),
        @XmlElement(name = "ToDoModRs", type = ToDoModRsType.class),
        @XmlElement(name = "ItemFixedAssetQueryRs", type = ItemFixedAssetQueryRsType.class),
        @XmlElement(name = "CreditMemoModRs", type = CreditMemoModRsType.class),
        @XmlElement(name = "EstimateModRs", type = EstimateModRsType.class),
        @XmlElement(name = "ItemInventoryModRs", type = ItemInventoryModRsType.class),
        @XmlElement(name = "InvoiceAddRs", type = InvoiceAddRsType.class),
        @XmlElement(name = "DataExtDefAddRs", type = DataExtDefAddRsType.class),
        @XmlElement(name = "SalesReceiptModRs", type = SalesReceiptModRsType.class),
        @XmlElement(name = "BillAddRs", type = BillAddRsType.class),
        @XmlElement(name = "ItemGroupQueryRs", type = ItemGroupQueryRsType.class),
        @XmlElement(name = "SalesOrderQueryRs", type = SalesOrderQueryRsType.class),
        @XmlElement(name = "ItemNonInventoryModRs", type = ItemNonInventoryModRsType.class),
        @XmlElement(name = "ItemAssembliesCanBuildQueryRs", type = ItemAssembliesCanBuildQueryRsType.class),
        @XmlElement(name = "ListDisplayModRs", type = ListDisplayModRsType.class),
        @XmlElement(name = "JournalEntryQueryRs", type = JournalEntryQueryRsType.class),
        @XmlElement(name = "BuildAssemblyAddRs", type = BuildAssemblyAddRsType.class),
        @XmlElement(name = "CreditMemoQueryRs", type = CreditMemoQueryRsType.class),
        @XmlElement(name = "BuildAssemblyQueryRs", type = BuildAssemblyQueryRsType.class),
        @XmlElement(name = "AlertAddRs", type = AlertAddRsType.class),
        @XmlElement(name = "ItemInventoryAssemblyModRs", type = ItemInventoryAssemblyModRsType.class),
        @XmlElement(name = "StandardTermsQueryRs", type = StandardTermsQueryRsType.class),
        @XmlElement(name = "ItemDiscountAddRs", type = ItemDiscountAddRsType.class),
        @XmlElement(name = "SalesRepModRs", type = SalesRepModRsType.class),
        @XmlElement(name = "EntityQueryRs", type = EntityQueryRsType.class),
        @XmlElement(name = "DataExtModRs", type = DataExtModRsType.class),
        @XmlElement(name = "CustomerAddRs", type = CustomerAddRsType.class),
        @XmlElement(name = "CreditMemoAddRs", type = CreditMemoAddRsType.class),
        @XmlElement(name = "PayrollItemNonWageQueryRs", type = PayrollItemNonWageQueryRsType.class),
        @XmlElement(name = "ItemSalesTaxQueryRs", type = ItemSalesTaxQueryRsType.class),
        @XmlElement(name = "WorkersCompCodeQueryRs", type = WorkersCompCodeQueryRsType.class),
        @XmlElement(name = "PayrollItemWageQueryRs", type = PayrollItemWageQueryRsType.class),
        @XmlElement(name = "SalesTaxReturnQueryRs", type = SalesTaxReturnQueryRsType.class),
        @XmlElement(name = "BillingRateQueryRs", type = BillingRateQueryRsType.class),
        @XmlElement(name = "JournalEntryModRs", type = JournalEntryModRsType.class),
        @XmlElement(name = "CustomerMsgQueryRs", type = CustomerMsgQueryRsType.class),
        @XmlElement(name = "JournalEntryAddRs", type = JournalEntryAddRsType.class),
        @XmlElement(name = "BillPaymentCheckModRs", type = BillPaymentCheckModRsType.class),
        @XmlElement(name = "PurchaseOrderQueryRs", type = PurchaseOrderQueryRsType.class),
        @XmlElement(name = "ItemSalesTaxGroupAddRs", type = ItemSalesTaxGroupAddRsType.class),
        @XmlElement(name = "TransferInventoryModRs", type = TransferInventoryModRsType.class),
        @XmlElement(name = "ItemServiceAddRs", type = ItemServiceAddRsType.class),
        @XmlElement(name = "BillPaymentCreditCardAddRs", type = BillPaymentCreditCardAddRsType.class),
        @XmlElement(name = "ClearedStatusModRs", type = ClearedStatusModRsType.class),
        @XmlElement(name = "PayrollItemWageModRs", type = PayrollItemWageModRsType.class),
        @XmlElement(name = "TemplateQueryRs", type = TemplateQueryRsType.class),
        @XmlElement(name = "InvoiceModRs", type = InvoiceModRsType.class),
        @XmlElement(name = "CustomSummaryReportQueryRs", type = CustomSummaryReportQueryRsType.class),
        @XmlElement(name = "ShipMethodQueryRs", type = ShipMethodQueryRsType.class),
        @XmlElement(name = "ItemSalesTaxModRs", type = ItemSalesTaxModRsType.class),
        @XmlElement(name = "OtherNameModRs", type = OtherNameModRsType.class),
        @XmlElement(name = "PayrollItemTaxAddRs", type = PayrollItemTaxAddRsType.class),
        @XmlElement(name = "PriceLevelAddRs", type = PriceLevelAddRsType.class),
        @XmlElement(name = "ItemInventoryAssemblyQueryRs", type = ItemInventoryAssemblyQueryRsType.class),
        @XmlElement(name = "DataExtDefModRs", type = DataExtDefModRsType.class),
        @XmlElement(name = "SalesTaxPayableQueryRs", type = SalesTaxPayableQueryRsType.class),
        @XmlElement(name = "ReceivePaymentModRs", type = ReceivePaymentModRsType.class),
        @XmlElement(name = "CustomDetailReportQueryRs", type = CustomDetailReportQueryRsType.class),
        @XmlElement(name = "PayrollItemQueryRs", type = PayrollItemQueryRsType.class),
        @XmlElement(name = "TransferInventoryAddRs", type = TransferInventoryAddRsType.class),
        @XmlElement(name = "PayrollItemDirectDepositAddRs", type = PayrollItemDirectDepositAddRsType.class),
        @XmlElement(name = "BudgetSummaryReportQueryRs", type = BudgetSummaryReportQueryRsType.class),
        @XmlElement(name = "UnitOfMeasureSetQueryRs", type = UnitOfMeasureSetQueryRsType.class),
        @XmlElement(name = "VendorCreditQueryRs", type = VendorCreditQueryRsType.class),
        @XmlElement(name = "TxnVoidRs", type = TxnVoidRsType.class),
        @XmlElement(name = "ToDoQueryRs", type = ToDoQueryRsType.class),
        @XmlElement(name = "PaymentMethodQueryRs", type = PaymentMethodQueryRsType.class),
        @XmlElement(name = "CheckModRs", type = CheckModRsType.class),
        @XmlElement(name = "SpecialAccountAddRs", type = SpecialAccountAddRsType.class),
        @XmlElement(name = "TimeReportQueryRs", type = TimeReportQueryRsType.class),
        @XmlElement(name = "ItemSalesTaxGroupQueryRs", type = ItemSalesTaxGroupQueryRsType.class),
        @XmlElement(name = "TxnDelRs", type = TxnDelRsType.class),
        @XmlElement(name = "ItemPaymentQueryRs", type = ItemPaymentQueryRsType.class),
        @XmlElement(name = "ReceivePaymentToDepositQueryRs", type = ReceivePaymentToDepositQueryRsType.class),
        @XmlElement(name = "SalesRepQueryRs", type = SalesRepQueryRsType.class),
        @XmlElement(name = "InventoryAdjustmentAddRs", type = InventoryAdjustmentAddRsType.class),
        @XmlElement(name = "CreditCardCreditModRs", type = CreditCardCreditModRsType.class),
        @XmlElement(name = "ListDisplayAddRs", type = ListDisplayAddRsType.class),
        @XmlElement(name = "GeneralDetailReportQueryRs", type = GeneralDetailReportQueryRsType.class),
        @XmlElement(name = "BillPaymentCheckAddRs", type = BillPaymentCheckAddRsType.class),
        @XmlElement(name = "Form1099CategoryAccountMappingModRs", type = Form1099CategoryAccountMappingModRsType.class)
    })
    protected List<Object> hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs;
    @XmlAttribute
    protected String newMessageSetID;
    @XmlAttribute
    protected BigInteger messageSetStatusCode;

    /**
     * Gets the value of the hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemReceiptAddRsType }
     * {@link CreditCardChargeQueryRsType }
     * {@link ItemPaymentAddRsType }
     * {@link AgingReportQueryRsType }
     * {@link PayrollYearToDateAdjustmentQueryRsType }
     * {@link BuildAssemblyModRsType }
     * {@link OtherNameAddRsType }
     * {@link SalesOrderAddRsType }
     * {@link CreditCardChargeAddRsType }
     * {@link SalesTaxCodeAddRsType }
     * {@link PriceLevelQueryRsType }
     * {@link VehicleModRsType }
     * {@link InvoiceQueryRsType }
     * {@link CustomerMsgAddRsType }
     * {@link CurrencyQueryRsType }
     * {@link SalesReceiptAddRsType }
     * {@link PayrollLiabilityAdjustmentQueryRsType }
     * {@link ReceivePaymentQueryRsType }
     * {@link PriceLevelModRsType }
     * {@link StandardTermsAddRsType }
     * {@link PayrollItemAdditionModRsType }
     * {@link PaycheckQueryRsType }
     * {@link InventoryAdjustmentModRsType }
     * {@link EmployeeDefaultModRsType }
     * {@link VehicleQueryRsType }
     * {@link TimeTrackingAddRsType }
     * {@link DateDrivenTermsQueryRsType }
     * {@link JobTypeAddRsType }
     * {@link ItemServiceQueryRsType }
     * {@link JobTypeQueryRsType }
     * {@link ReceivePaymentAddRsType }
     * {@link ListDelRsType }
     * {@link EmployeeModRsType }
     * {@link ItemFixedAssetModRsType }
     * {@link DataExtAddRsType }
     * {@link ItemSubtotalQueryRsType }
     * {@link EmployeeAddRsType }
     * {@link PayrollItemDeductionAddRsType }
     * {@link PayrollPriorPaymentAddRsType }
     * {@link UnitOfMeasureSetAddRsType }
     * {@link AccountQueryRsType }
     * {@link ItemGroupAddRsType }
     * {@link ItemInventoryQueryRsType }
     * {@link ItemNonInventoryAddRsType }
     * {@link TermsQueryRsType }
     * {@link ChargeModRsType }
     * {@link BillingRateAddRsType }
     * {@link CustomerTypeQueryRsType }
     * {@link VehicleMileageQueryRsType }
     * {@link ItemSitesQueryRsType }
     * {@link BillQueryRsType }
     * {@link ItemDiscountQueryRsType }
     * {@link SalesTaxCodeQueryRsType }
     * {@link TimeTrackingQueryRsType }
     * {@link ItemSalesTaxAddRsType }
     * {@link PurchaseOrderModRsType }
     * {@link CustomerQueryRsType }
     * {@link WorkersCompCodeModRsType }
     * {@link ItemSubtotalAddRsType }
     * {@link ItemSubtotalModRsType }
     * {@link CompanyActivityQueryRsType }
     * {@link AccountModRsType }
     * {@link AlertDelRsType }
     * {@link VendorAddRsType }
     * {@link PayrollLiabilityAdjustmentAddRsType }
     * {@link DataEventRecoveryInfoQueryRsType }
     * {@link CreditCardCreditQueryRsType }
     * {@link CheckQueryRsType }
     * {@link ItemFixedAssetAddRsType }
     * {@link AccountAddRsType }
     * {@link GeneralSummaryReportQueryRsType }
     * {@link DataEventRecoveryInfoDelRsType }
     * {@link DepositAddRsType }
     * {@link TimeTrackingModRsType }
     * {@link SalesRepAddRsType }
     * {@link DataExtDelRsType }
     * {@link PayrollLiabilityCheckQueryRsType }
     * {@link PayrollItemWageAddRsType }
     * {@link HostQueryRsType }
     * {@link CompanyQueryRsType }
     * {@link DataExtDefDelRsType }
     * {@link ClassModRsType }
     * {@link VendorCreditAddRsType }
     * {@link TransferInventoryQueryRsType }
     * {@link VendorTypeQueryRsType }
     * {@link VendorTypeAddRsType }
     * {@link DataExtDefQueryRsType }
     * {@link CustomerTypeAddRsType }
     * {@link ListDeletedQueryRsType }
     * {@link PreferencesModRsType }
     * {@link ARRefundCreditCardAddRsType }
     * {@link BillPaymentCreditCardQueryRsType }
     * {@link ShipMethodAddRsType }
     * {@link PayrollYearToDateAdjustmentAddRsType }
     * {@link ItemDiscountModRsType }
     * {@link ListMergeRsType }
     * {@link PayrollItemWorkersCompensationModRsType }
     * {@link PurchaseOrderAddRsType }
     * {@link InventorySiteAddRsType }
     * {@link TransactionQueryRsType }
     * {@link SpecialItemAddRsType }
     * {@link AlertQueryRsType }
     * {@link SalesTaxPaymentCheckModRsType }
     * {@link EmployeeDefaultQueryRsType }
     * {@link PayrollItemCompanyContributionAddRsType }
     * {@link EstimateAddRsType }
     * {@link ClassQueryRsType }
     * {@link CustomerModRsType }
     * {@link PayrollItemDirectDepositModRsType }
     * {@link ItemServiceModRsType }
     * {@link OtherNameQueryRsType }
     * {@link PayrollDetailReportQueryRsType }
     * {@link ItemPaymentModRsType }
     * {@link BillToPayQueryRsType }
     * {@link PayrollItemTaxModRsType }
     * {@link TxnDisplayAddRsType }
     * {@link CurrencyModRsType }
     * {@link SalesTaxPaymentCheckAddRsType }
     * {@link BillPaymentCheckQueryRsType }
     * {@link TxnDeletedQueryRsType }
     * {@link QBCommandExecRsType }
     * {@link VehicleAddRsType }
     * {@link PayrollItemAdditionAddRsType }
     * {@link ChargeAddRsType }
     * {@link DepositQueryRsType }
     * {@link WorkersCompCodeAddRsType }
     * {@link VendorModRsType }
     * {@link BillModRsType }
     * {@link EstimateQueryRsType }
     * {@link CreditCardCreditAddRsType }
     * {@link ClassAddRsType }
     * {@link PaymentMethodAddRsType }
     * {@link InventorySiteModRsType }
     * {@link ItemReceiptQueryRsType }
     * {@link ItemQueryRsType }
     * {@link ChargeQueryRsType }
     * {@link ItemNonInventoryQueryRsType }
     * {@link ItemOtherChargeModRsType }
     * {@link JobReportQueryRsType }
     * {@link PreferencesQueryRsType }
     * {@link TxnDisplayModRsType }
     * {@link ItemOtherChargeAddRsType }
     * {@link AccountTaxLineInfoQueryRsType }
     * {@link InventorySiteQueryRsType }
     * {@link PayrollSummaryReportQueryRsType }
     * {@link SalesTaxCodeModRsType }
     * {@link SalesTaxReturnLineQueryRsType }
     * {@link DepositModRsType }
     * {@link ItemInventoryAddRsType }
     * {@link CurrencyAddRsType }
     * {@link ItemReceiptModRsType }
     * {@link VendorCreditModRsType }
     * {@link CheckAddRsType }
     * {@link Form1099CategoryAccountMappingQueryRsType }
     * {@link ItemGroupModRsType }
     * {@link SalesOrderModRsType }
     * {@link PayrollItemCompanyContributionModRsType }
     * {@link DateDrivenTermsAddRsType }
     * {@link CreditCardChargeModRsType }
     * {@link PayrollPriorPaymentQueryRsType }
     * {@link SalesReceiptQueryRsType }
     * {@link EmployeeQueryRsType }
     * {@link ARRefundCreditCardQueryRsType }
     * {@link ToDoAddRsType }
     * {@link VehicleMileageAddRsType }
     * {@link ItemSalesTaxGroupModRsType }
     * {@link SalesTaxPaymentCheckQueryRsType }
     * {@link PayrollItemWorkersCompensationAddRsType }
     * {@link InventoryAdjustmentQueryRsType }
     * {@link VendorQueryRsType }
     * {@link ItemInventoryAssemblyAddRsType }
     * {@link PayrollItemDeductionModRsType }
     * {@link PayrollLastPeriodQueryRsType }
     * {@link ItemOtherChargeQueryRsType }
     * {@link ToDoModRsType }
     * {@link ItemFixedAssetQueryRsType }
     * {@link CreditMemoModRsType }
     * {@link EstimateModRsType }
     * {@link ItemInventoryModRsType }
     * {@link InvoiceAddRsType }
     * {@link DataExtDefAddRsType }
     * {@link SalesReceiptModRsType }
     * {@link BillAddRsType }
     * {@link ItemGroupQueryRsType }
     * {@link SalesOrderQueryRsType }
     * {@link ItemNonInventoryModRsType }
     * {@link ItemAssembliesCanBuildQueryRsType }
     * {@link ListDisplayModRsType }
     * {@link JournalEntryQueryRsType }
     * {@link BuildAssemblyAddRsType }
     * {@link CreditMemoQueryRsType }
     * {@link BuildAssemblyQueryRsType }
     * {@link AlertAddRsType }
     * {@link ItemInventoryAssemblyModRsType }
     * {@link StandardTermsQueryRsType }
     * {@link ItemDiscountAddRsType }
     * {@link SalesRepModRsType }
     * {@link EntityQueryRsType }
     * {@link DataExtModRsType }
     * {@link CustomerAddRsType }
     * {@link CreditMemoAddRsType }
     * {@link PayrollItemNonWageQueryRsType }
     * {@link ItemSalesTaxQueryRsType }
     * {@link WorkersCompCodeQueryRsType }
     * {@link PayrollItemWageQueryRsType }
     * {@link SalesTaxReturnQueryRsType }
     * {@link BillingRateQueryRsType }
     * {@link JournalEntryModRsType }
     * {@link CustomerMsgQueryRsType }
     * {@link JournalEntryAddRsType }
     * {@link BillPaymentCheckModRsType }
     * {@link PurchaseOrderQueryRsType }
     * {@link ItemSalesTaxGroupAddRsType }
     * {@link TransferInventoryModRsType }
     * {@link ItemServiceAddRsType }
     * {@link BillPaymentCreditCardAddRsType }
     * {@link ClearedStatusModRsType }
     * {@link PayrollItemWageModRsType }
     * {@link TemplateQueryRsType }
     * {@link InvoiceModRsType }
     * {@link CustomSummaryReportQueryRsType }
     * {@link ShipMethodQueryRsType }
     * {@link ItemSalesTaxModRsType }
     * {@link OtherNameModRsType }
     * {@link PayrollItemTaxAddRsType }
     * {@link PriceLevelAddRsType }
     * {@link ItemInventoryAssemblyQueryRsType }
     * {@link DataExtDefModRsType }
     * {@link SalesTaxPayableQueryRsType }
     * {@link ReceivePaymentModRsType }
     * {@link CustomDetailReportQueryRsType }
     * {@link PayrollItemQueryRsType }
     * {@link TransferInventoryAddRsType }
     * {@link PayrollItemDirectDepositAddRsType }
     * {@link BudgetSummaryReportQueryRsType }
     * {@link UnitOfMeasureSetQueryRsType }
     * {@link VendorCreditQueryRsType }
     * {@link TxnVoidRsType }
     * {@link ToDoQueryRsType }
     * {@link PaymentMethodQueryRsType }
     * {@link CheckModRsType }
     * {@link SpecialAccountAddRsType }
     * {@link TimeReportQueryRsType }
     * {@link ItemSalesTaxGroupQueryRsType }
     * {@link TxnDelRsType }
     * {@link ItemPaymentQueryRsType }
     * {@link ReceivePaymentToDepositQueryRsType }
     * {@link SalesRepQueryRsType }
     * {@link InventoryAdjustmentAddRsType }
     * {@link CreditCardCreditModRsType }
     * {@link ListDisplayAddRsType }
     * {@link GeneralDetailReportQueryRsType }
     * {@link BillPaymentCheckAddRsType }
     * {@link Form1099CategoryAccountMappingModRsType }
     * 
     * 
     */
    public List<Object> getHostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs() {
        if (hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs == null) {
            hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs = new ArrayList<Object>();
        }
        return this.hostQueryRsOrCompanyQueryRsOrCompanyActivityQueryRs;
    }

    /**
     * Gets the value of the newMessageSetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewMessageSetID() {
        return newMessageSetID;
    }

    /**
     * Sets the value of the newMessageSetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewMessageSetID(String value) {
        this.newMessageSetID = value;
    }

    /**
     * Gets the value of the messageSetStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMessageSetStatusCode() {
        return messageSetStatusCode;
    }

    /**
     * Sets the value of the messageSetStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMessageSetStatusCode(BigInteger value) {
        this.messageSetStatusCode = value;
    }

}
